### ISSUE TITLE
All psycopg3 documentation links are 404

### ISSUE THREAD

**Issue by j-bennet** [psycopg/psycopg-website#12]
Any docs here. https://www.psycopg.org/psycopg3/docs/

**Comment by dvarrazzo** [comment]
Thank you. This build failed. https://github.com/psycopg/psycopg-website/runs/5612077645?check_suite_focus=true#step:6:366

**Comment by dvarrazzo** [comment]
Fixed, thank you. Caused by https://github.com/psycopg/psycopg/issues/252.
